version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - /postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  redis:
    image: redis
    container_name: cache
    restart: always
    volumes:
      - /redis-data:/var/lib/redis
    ports:
      - 6379:6379
    networks:
        node_net:
          ipv4_address: 172.28.1.4
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
